name: Deploy
on:
  push:
    branches:
      - main
jobs:
  pull:
    name: Run Pull
    runs-on: ubuntu-latest
    steps:
    - name: GITHUB_WORKSPACE
      run: |
        echo $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: LIST WORKSPACE DIR
      run: |
        cd $GITHUB_WORKSPACE/project/project
        ls -al
    - name: SHOW ENVS
      run: |
        echo "ACTIONS_SSH_KEY => ..."
    - name: Copy Files to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.ACTIONS_SSH_KEY }}
        source: 'project/project/*'
        target: ${{ secrets.WORK_DIR }}

    