# name: Deploy Package to NPM

# on:
#   push:
#     tags:
#       - 'v[0-9]+.[0-9]+.[0-9]+'
# jobs:
#   publish_npm:
#     name: Publishing to NPM

#     runs-on: ubuntu-latest

#     permissions:
#       actions:
#         write
#       contents:
#         write

#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup NodeJs
#         uses: actions/setup-node@v3
#         with:
#           node-version: x.y # Version that you want use here
#           registry-url: https://registry.npmjs.org/
                    
#       - name: Install Packages
#         run: yarn

name: Bump version
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Set Git user name and email
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Bump version
        run: |
          npm version patch --git-tag-version false 
      - name: Status
        run: |
          git status
      - name: Refs
        run: |
          git show-ref
      - name: Commit
        run: |
          git commit -m "bump"
      - name: Commit version bump
        run: |
          git push origin main