on:
  create:
    tags:
      - 'refs/tags/*'
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      
      - name: Extract Tag Name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Echo Tag name
        run: |
          TAG=${{ env.TAG }}
          echo $TAG
          
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TOKEN_GH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "GitHub Actions"
      - name: set origin
        run: |
          git remote set-url origin ${{secrets.REPOSITORY}}

      - name: Set Version in package.json
        run: |
          TAG=${{ env.TAG }}
          VERSION=$(echo $TAG | sed 's/v//')
          echo "Updating package.json version to $VERSION"
          # Update package.json version
          jq ".version = \"$VERSION\"" package.json > tmp.json && mv tmp.json package.json

      - name: Commit and push
        run: |
          git add package.json
          git commit -m "Bump version to $(jq -r '.version' package.json) [skip ci]"
          git push origin HEAD:main