name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    # - name: Build Storybook
    #   run: npm run build-storybook
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        npm run playwright
    # - name: Run Playwright tests
    #   run: |
    #     npm run tests
    #     # Capture the exit code of the last command
    #     exit_code=$?
    #     # Save the exit code to an environment file
    #     echo "PLAYWRIGHT_TESTS_EXIT_CODE=$exit_code" > playwright_tests_env
    # - name: Check Playwright test results
    #   run: |
    #     exit_code=$(cat playwright_tests_env | grep 'PLAYWRIGHT_TESTS_EXIT_CODE' | cut -d'=' -f2)
    #     if [ $exit_code -ne 0 ]; then
    #       echo "Playwright tests failed with exit code $exit_code"
    #       exit 1
    #     fi
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
